// Decompile from assembly: Assembly-CSharp.dll

using System;

public enum CharacterDefaultAnimationKey
{
	DEPRECATED_1,
	VOICELINE,
	HOLOGRAM,
	STORE_IDLE,
	CHARACTER_SELECT_IDLE,
	VICTORY_POSE,
	SECONDARY_STORE_IDLE,
	SECONDARY_CHARACTER_SELECT_IDLE,
	SWAP_IN_ANIMATION,
	SWAP_OUT_ANIMATION,
	VICTORY_POSE_LOOP,
	MAIN_MENU
}
