using System;
using System.Collections.Generic;

// Token: 0x020002E4 RID: 740
public class SoundMap
{
	// Token: 0x06000F61 RID: 3937 RVA: 0x0005D500 File Offset: 0x0005B900
	public string GetFileName(SoundKey key)
	{
		string result;
		this.fileNames.TryGetValue(key, out result);
		return result;
	}

	// Token: 0x06000F62 RID: 3938 RVA: 0x0005D520 File Offset: 0x0005B920
	public string GetAssetName(SoundKey key)
	{
		string result;
		this.assetNames.TryGetValue(key, out result);
		return result;
	}

	// Token: 0x06000F63 RID: 3939 RVA: 0x0005D540 File Offset: 0x0005B940
	public string GetBundleName(SoundBundleKey key)
	{
		string result;
		this.bundleNames.TryGetValue(key, out result);
		return result;
	}

	// Token: 0x06000F64 RID: 3940 RVA: 0x0005D560 File Offset: 0x0005B960
	public SoundKey[] GetBundleSounds(SoundBundleKey key)
	{
		SoundKey[] result;
		this.bundleSounds.TryGetValue(key, out result);
		return result;
	}

	// Token: 0x04000A0A RID: 2570
	private Dictionary<SoundKey, string> fileNames = new Dictionary<SoundKey, string>
	{
		{
			SoundKey.generic_buttonHighlight,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_dialogOpen,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_dialogClose,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_arrowClickLeft,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_arrowClickRight,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_dropdownOpen,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_dropdownClose,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_toggleOn,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_toggleOff,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_typingCharacter,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_typingBackspace,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_screenForwardTransition,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_screenBackTransition,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_dynamicMoveActivate,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_powerMoveActivate,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_dynamicMoveDenied,
			"generic.assetbundle"
		},
		{
			SoundKey.generic_powerMoveDenied,
			"generic.assetbundle"
		},
		{
			SoundKey.wavedashArena_music,
			"wavedashArena.assetbundle"
		},
		{
			SoundKey.cryoStation_music,
			"cryoStation.assetbundle"
		},
		{
			SoundKey.combatLab_music,
			"combatLab.assetbundle"
		},
		{
			SoundKey.combatLabAlt_music,
			"combatLabAlt.assetbundle"
		},
		{
			SoundKey.maluMalu_music,
			"maluMalu.assetbundle"
		},
		{
			SoundKey.maluMaluAlt_music,
			"maluMaluAlt.assetbundle"
		},
		{
			SoundKey.forbiddenShrine_music,
			"forbiddenShrine.assetbundle"
		},
		{
			SoundKey.forbiddenShrineAlt_music,
			"forbiddenShrineAlt.assetbundle"
		},
		{
			SoundKey.shadowbriar_music,
			"shadowbriar.assetbundle"
		},
		{
			SoundKey.shadowbriarAlt_music,
			"shadowbriarAlt.assetbundle"
		},
		{
			SoundKey.cargo_music,
			"cargo.assetbundle"
		},
		{
			SoundKey.ashaniPostGame_levelup,
			"ashaniPostGame.assetbundle"
		},
		{
			SoundKey.kiddPostGame_levelup,
			"kiddPostGame.assetbundle"
		},
		{
			SoundKey.xanaPostGame_levelup,
			"xanaPostGame.assetbundle"
		},
		{
			SoundKey.raymerPostGame_levelup,
			"raymerPostGame.assetbundle"
		},
		{
			SoundKey.zhurongPostGame_levelup,
			"zhurongPostGame.assetbundle"
		},
		{
			SoundKey.afiPostGame_levelup,
			"afiPostGame.assetbundle"
		},
		{
			SoundKey.weishanPostGame_levelup,
			"weishanPostGame.assetbundle"
		},
		{
			SoundKey.ashaniStore_purchaseItem,
			"ashaniStore.assetbundle"
		},
		{
			SoundKey.kiddStore_purchaseItem,
			"kiddStore.assetbundle"
		},
		{
			SoundKey.xanaStore_purchaseItem,
			"xanaStore.assetbundle"
		},
		{
			SoundKey.raymerStore_purchaseItem,
			"raymerStore.assetbundle"
		},
		{
			SoundKey.zhurongStore_purchaseItem,
			"zhurongStore.assetbundle"
		},
		{
			SoundKey.afiStore_purchaseItem,
			"afiStore.assetbundle"
		},
		{
			SoundKey.weishanStore_purchaseItem,
			"weishanStore.assetbundle"
		},
		{
			SoundKey.login_accountCreationConfirmed,
			"login.assetbundle"
		},
		{
			SoundKey.login_accountCreationError,
			"login.assetbundle"
		},
		{
			SoundKey.mainMenu_music,
			"mainMenu.assetbundle"
		},
		{
			SoundKey.mainMenu_mainMenuFoldoutOpen,
			"mainMenu.assetbundle"
		},
		{
			SoundKey.mainMenu_mainMenuFoldoutClose,
			"mainMenu.assetbundle"
		},
		{
			SoundKey.mainMenu_queueStart,
			"mainMenu.assetbundle"
		},
		{
			SoundKey.mainMenu_queueStop,
			"mainMenu.assetbundle"
		},
		{
			SoundKey.characterSelect_characterSelectScreenOpen,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_onlineBlindPickScreenOpen,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_characterHighlight,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_characterSelect,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_characterDeselect,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_randomHighlight,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_randomSelect,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_randomDeselect,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_skinCycle,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_teamCycle,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_totemPartnerCycle,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_ruleSetDelete,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_ruleSetAdd,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.characterSelect_ruleSetSelect,
			"characterSelect.assetbundle"
		},
		{
			SoundKey.stageSelect_stageSelectScreenOpen,
			"stageSelect.assetbundle"
		},
		{
			SoundKey.stageSelect_stageStrike,
			"stageSelect.assetbundle"
		},
		{
			SoundKey.stageSelect_stageUnstrike,
			"stageSelect.assetbundle"
		},
		{
			SoundKey.stageSelect_stageStikesReset,
			"stageSelect.assetbundle"
		},
		{
			SoundKey.loadingBattle_loadingBattleScreenOpen,
			"loadingBattle.assetbundle"
		},
		{
			SoundKey.inGame_exitGame,
			"inGame.assetbundle"
		},
		{
			SoundKey.inGame_endGame,
			"inGame.assetbundle"
		},
		{
			SoundKey.inGame_pause,
			"inGame.assetbundle"
		},
		{
			SoundKey.inGame_unpause,
			"inGame.assetbundle"
		},
		{
			SoundKey.inGame_flyout,
			"inGame.assetbundle"
		},
		{
			SoundKey.inGame_flyout_small,
			"inGame.assetbundle"
		},
		{
			SoundKey.inGame_tumbleHitGround,
			"inGame.assetbundle"
		},
		{
			SoundKey.victoryScreen_victoryScreenOpen,
			"victoryScreen.assetbundle"
		},
		{
			SoundKey.playerProgression_playerProgressionScreenOpen,
			"playerProgression.assetbundle"
		},
		{
			SoundKey.playerProgression_experienceTick,
			"playerProgression.assetbundle"
		},
		{
			SoundKey.playerProgression_levelUp,
			"playerProgression.assetbundle"
		},
		{
			SoundKey.customLobby_customLobbyScreenOpen,
			"customLobby.assetbundle"
		},
		{
			SoundKey.customLobby_customLobbyPlayerJoined,
			"customLobby.assetbundle"
		},
		{
			SoundKey.customLobby_customLobbyPlayerLeft,
			"customLobby.assetbundle"
		},
		{
			SoundKey.settings_settingsScreenOpen,
			"settings.assetbundle"
		},
		{
			SoundKey.settings_controlBindingSelect,
			"settings.assetbundle"
		},
		{
			SoundKey.settings_controlBindingSet,
			"settings.assetbundle"
		},
		{
			SoundKey.settings_settingsReset,
			"settings.assetbundle"
		},
		{
			SoundKey.settings_settingsTabChange,
			"settings.assetbundle"
		},
		{
			SoundKey.settings_soundEffectSliderSet,
			"settings.assetbundle"
		},
		{
			SoundKey.store_music,
			"store.assetbundle"
		},
		{
			SoundKey.store_storeScreenOpen,
			"store.assetbundle"
		},
		{
			SoundKey.store_characterEquipViewOpen,
			"store.assetbundle"
		},
		{
			SoundKey.store_characterEquipViewClosed,
			"store.assetbundle"
		},
		{
			SoundKey.store_collectiblesEquipViewOpen,
			"store.assetbundle"
		},
		{
			SoundKey.store_collectiblesEquipViewClosed,
			"store.assetbundle"
		},
		{
			SoundKey.store_miniCharacterSelected,
			"store.assetbundle"
		},
		{
			SoundKey.store_categorySelected,
			"store.assetbundle"
		},
		{
			SoundKey.store_equipmentSelected,
			"store.assetbundle"
		},
		{
			SoundKey.store_itemEquip,
			"store.assetbundle"
		},
		{
			SoundKey.store_storeTabChange,
			"store.assetbundle"
		},
		{
			SoundKey.store_purchaseDialogOpened,
			"store.assetbundle"
		},
		{
			SoundKey.store_purchaseConfirmed,
			"store.assetbundle"
		},
		{
			SoundKey.unboxing_music,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_openUnboxingScene,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_exitUnboxingScene,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_clickOpenBox,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_clickOpenBoxButton,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_crystalDrop,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_portalAppear,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_blueFlashSide,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_blueFlashCenter,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_highlight,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_currency,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemSideCommon,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemSideUncommon,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemSideRare,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemSideLegendary,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemCenterCommon,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemCenterUncommon,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemCenterRare,
			"unboxing.assetbundle"
		},
		{
			SoundKey.unboxing_itemCenterLegendary,
			"unboxing.assetbundle"
		},
		{
			SoundKey.credits_music,
			"credits.assetbundle"
		}
	};

	// Token: 0x04000A0B RID: 2571
	private Dictionary<SoundKey, string> assetNames = new Dictionary<SoundKey, string>
	{
		{
			SoundKey.generic_buttonHighlight,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/buttonHighlight.asset"
		},
		{
			SoundKey.generic_dialogOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/dialogOpen.asset"
		},
		{
			SoundKey.generic_dialogClose,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/dialogClose.asset"
		},
		{
			SoundKey.generic_arrowClickLeft,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/arrowClickLeft.asset"
		},
		{
			SoundKey.generic_arrowClickRight,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/arrowClickRight.asset"
		},
		{
			SoundKey.generic_dropdownOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/dropdownOpen.asset"
		},
		{
			SoundKey.generic_dropdownClose,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/dropdownClose.asset"
		},
		{
			SoundKey.generic_toggleOn,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/toggleOn.asset"
		},
		{
			SoundKey.generic_toggleOff,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/toggleOff.asset"
		},
		{
			SoundKey.generic_typingCharacter,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/typingCharacter.asset"
		},
		{
			SoundKey.generic_typingBackspace,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/typingBackspace.asset"
		},
		{
			SoundKey.generic_screenForwardTransition,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/screenForwardTransition.asset"
		},
		{
			SoundKey.generic_screenBackTransition,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/screenBackTransition.asset"
		},
		{
			SoundKey.generic_dynamicMoveActivate,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/dynamicMoveActivate.asset"
		},
		{
			SoundKey.generic_powerMoveActivate,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/powerMoveActivate.asset"
		},
		{
			SoundKey.generic_dynamicMoveDenied,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/dynamicMoveDenied.asset"
		},
		{
			SoundKey.generic_powerMoveDenied,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/generic/powerMoveDenied.asset"
		},
		{
			SoundKey.wavedashArena_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/wavedashArena/music.asset"
		},
		{
			SoundKey.cryoStation_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/cryoStation/music.asset"
		},
		{
			SoundKey.combatLab_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/combatLab/music.asset"
		},
		{
			SoundKey.combatLabAlt_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/combatLabAlt/music.asset"
		},
		{
			SoundKey.maluMalu_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/maluMalu/music.asset"
		},
		{
			SoundKey.maluMaluAlt_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/maluMaluAlt/music.asset"
		},
		{
			SoundKey.forbiddenShrine_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/forbiddenShrine/music.asset"
		},
		{
			SoundKey.forbiddenShrineAlt_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/forbiddenShrineAlt/music.asset"
		},
		{
			SoundKey.shadowbriar_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/shadowbriar/music.asset"
		},
		{
			SoundKey.shadowbriarAlt_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/shadowbriarAlt/music.asset"
		},
		{
			SoundKey.cargo_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/cargo/music.asset"
		},
		{
			SoundKey.ashaniPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/ashaniPostGame/levelup.asset"
		},
		{
			SoundKey.kiddPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/kiddPostGame/levelup.asset"
		},
		{
			SoundKey.xanaPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/xanaPostGame/levelup.asset"
		},
		{
			SoundKey.raymerPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/raymerPostGame/levelup.asset"
		},
		{
			SoundKey.zhurongPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/zhurongPostGame/levelup.asset"
		},
		{
			SoundKey.afiPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/afiPostGame/levelup.asset"
		},
		{
			SoundKey.weishanPostGame_levelup,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/weishanPostGame/levelup.asset"
		},
		{
			SoundKey.ashaniStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/ashaniStore/purchaseItem.asset"
		},
		{
			SoundKey.kiddStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/kiddStore/purchaseItem.asset"
		},
		{
			SoundKey.xanaStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/xanaStore/purchaseItem.asset"
		},
		{
			SoundKey.raymerStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/raymerStore/purchaseItem.asset"
		},
		{
			SoundKey.zhurongStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/zhurongStore/purchaseItem.asset"
		},
		{
			SoundKey.afiStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/afiStore/purchaseItem.asset"
		},
		{
			SoundKey.weishanStore_purchaseItem,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/weishanStore/purchaseItem.asset"
		},
		{
			SoundKey.login_accountCreationConfirmed,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/login/accountCreationConfirmed.asset"
		},
		{
			SoundKey.login_accountCreationError,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/login/accountCreationError.asset"
		},
		{
			SoundKey.mainMenu_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/mainMenu/music.asset"
		},
		{
			SoundKey.mainMenu_mainMenuFoldoutOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/mainMenu/mainMenuFoldoutOpen.asset"
		},
		{
			SoundKey.mainMenu_mainMenuFoldoutClose,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/mainMenu/mainMenuFoldoutClose.asset"
		},
		{
			SoundKey.mainMenu_queueStart,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/mainMenu/queueStart.asset"
		},
		{
			SoundKey.mainMenu_queueStop,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/mainMenu/queueStop.asset"
		},
		{
			SoundKey.characterSelect_characterSelectScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/characterSelectScreenOpen.asset"
		},
		{
			SoundKey.characterSelect_onlineBlindPickScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/onlineBlindPickScreenOpen.asset"
		},
		{
			SoundKey.characterSelect_characterHighlight,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/characterHighlight.asset"
		},
		{
			SoundKey.characterSelect_characterSelect,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/characterSelect.asset"
		},
		{
			SoundKey.characterSelect_characterDeselect,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/characterDeselect.asset"
		},
		{
			SoundKey.characterSelect_randomHighlight,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/randomHighlight.asset"
		},
		{
			SoundKey.characterSelect_randomSelect,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/randomSelect.asset"
		},
		{
			SoundKey.characterSelect_randomDeselect,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/randomDeselect.asset"
		},
		{
			SoundKey.characterSelect_skinCycle,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/skinCycle.asset"
		},
		{
			SoundKey.characterSelect_teamCycle,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/teamCycle.asset"
		},
		{
			SoundKey.characterSelect_totemPartnerCycle,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/totemPartnerCycle.asset"
		},
		{
			SoundKey.characterSelect_ruleSetDelete,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/ruleSetDelete.asset"
		},
		{
			SoundKey.characterSelect_ruleSetAdd,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/ruleSetAdd.asset"
		},
		{
			SoundKey.characterSelect_ruleSetSelect,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/characterSelect/ruleSetSelect.asset"
		},
		{
			SoundKey.stageSelect_stageSelectScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/stageSelect/stageSelectScreenOpen.asset"
		},
		{
			SoundKey.stageSelect_stageStrike,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/stageSelect/stageStrike.asset"
		},
		{
			SoundKey.stageSelect_stageUnstrike,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/stageSelect/stageUnstrike.asset"
		},
		{
			SoundKey.stageSelect_stageStikesReset,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/stageSelect/stageStikesReset.asset"
		},
		{
			SoundKey.loadingBattle_loadingBattleScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/loadingBattle/loadingBattleScreenOpen.asset"
		},
		{
			SoundKey.inGame_exitGame,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/exitGame.asset"
		},
		{
			SoundKey.inGame_endGame,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/endGame.asset"
		},
		{
			SoundKey.inGame_pause,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/pause.asset"
		},
		{
			SoundKey.inGame_unpause,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/unpause.asset"
		},
		{
			SoundKey.inGame_flyout,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/flyout.asset"
		},
		{
			SoundKey.inGame_flyout_small,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/flyout_small.asset"
		},
		{
			SoundKey.inGame_tumbleHitGround,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/inGame/tumbleHitGround.asset"
		},
		{
			SoundKey.victoryScreen_victoryScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/victoryScreen/victoryScreenOpen.asset"
		},
		{
			SoundKey.playerProgression_playerProgressionScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/playerProgression/playerProgressionScreenOpen.asset"
		},
		{
			SoundKey.playerProgression_experienceTick,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/playerProgression/experienceTick.asset"
		},
		{
			SoundKey.playerProgression_levelUp,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/playerProgression/levelUp.asset"
		},
		{
			SoundKey.customLobby_customLobbyScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/customLobby/customLobbyScreenOpen.asset"
		},
		{
			SoundKey.customLobby_customLobbyPlayerJoined,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/customLobby/customLobbyPlayerJoined.asset"
		},
		{
			SoundKey.customLobby_customLobbyPlayerLeft,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/customLobby/customLobbyPlayerLeft.asset"
		},
		{
			SoundKey.settings_settingsScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/settings/settingsScreenOpen.asset"
		},
		{
			SoundKey.settings_controlBindingSelect,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/settings/controlBindingSelect.asset"
		},
		{
			SoundKey.settings_controlBindingSet,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/settings/controlBindingSet.asset"
		},
		{
			SoundKey.settings_settingsReset,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/settings/settingsReset.asset"
		},
		{
			SoundKey.settings_settingsTabChange,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/settings/settingsTabChange.asset"
		},
		{
			SoundKey.settings_soundEffectSliderSet,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/settings/soundEffectSliderSet.asset"
		},
		{
			SoundKey.store_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/music.asset"
		},
		{
			SoundKey.store_storeScreenOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/storeScreenOpen.asset"
		},
		{
			SoundKey.store_characterEquipViewOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/characterEquipViewOpen.asset"
		},
		{
			SoundKey.store_characterEquipViewClosed,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/characterEquipViewClosed.asset"
		},
		{
			SoundKey.store_collectiblesEquipViewOpen,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/collectiblesEquipViewOpen.asset"
		},
		{
			SoundKey.store_collectiblesEquipViewClosed,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/collectiblesEquipViewClosed.asset"
		},
		{
			SoundKey.store_miniCharacterSelected,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/miniCharacterSelected.asset"
		},
		{
			SoundKey.store_categorySelected,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/categorySelected.asset"
		},
		{
			SoundKey.store_equipmentSelected,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/equipmentSelected.asset"
		},
		{
			SoundKey.store_itemEquip,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/itemEquip.asset"
		},
		{
			SoundKey.store_storeTabChange,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/storeTabChange.asset"
		},
		{
			SoundKey.store_purchaseDialogOpened,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/purchaseDialogOpened.asset"
		},
		{
			SoundKey.store_purchaseConfirmed,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/store/purchaseConfirmed.asset"
		},
		{
			SoundKey.unboxing_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/music.asset"
		},
		{
			SoundKey.unboxing_openUnboxingScene,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/openUnboxingScene.asset"
		},
		{
			SoundKey.unboxing_exitUnboxingScene,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/exitUnboxingScene.asset"
		},
		{
			SoundKey.unboxing_clickOpenBox,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/clickOpenBox.asset"
		},
		{
			SoundKey.unboxing_clickOpenBoxButton,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/clickOpenBoxButton.asset"
		},
		{
			SoundKey.unboxing_crystalDrop,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/crystalDrop.asset"
		},
		{
			SoundKey.unboxing_portalAppear,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/portalAppear.asset"
		},
		{
			SoundKey.unboxing_blueFlashSide,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/blueFlashSide.asset"
		},
		{
			SoundKey.unboxing_blueFlashCenter,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/blueFlashCenter.asset"
		},
		{
			SoundKey.unboxing_highlight,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/highlight.asset"
		},
		{
			SoundKey.unboxing_currency,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/currency.asset"
		},
		{
			SoundKey.unboxing_itemSideCommon,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemSideCommon.asset"
		},
		{
			SoundKey.unboxing_itemSideUncommon,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemSideUncommon.asset"
		},
		{
			SoundKey.unboxing_itemSideRare,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemSideRare.asset"
		},
		{
			SoundKey.unboxing_itemSideLegendary,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemSideLegendary.asset"
		},
		{
			SoundKey.unboxing_itemCenterCommon,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemCenterCommon.asset"
		},
		{
			SoundKey.unboxing_itemCenterUncommon,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemCenterUncommon.asset"
		},
		{
			SoundKey.unboxing_itemCenterRare,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemCenterRare.asset"
		},
		{
			SoundKey.unboxing_itemCenterLegendary,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/unboxing/itemCenterLegendary.asset"
		},
		{
			SoundKey.credits_music,
			"Assets/_ASSETBUNDLE_SOURCE/Sound/credits/music.asset"
		}
	};

	// Token: 0x04000A0C RID: 2572
	private Dictionary<SoundBundleKey, string> bundleNames = new Dictionary<SoundBundleKey, string>
	{
		{
			SoundBundleKey.generic,
			"generic.assetbundle"
		},
		{
			SoundBundleKey.wavedashArena,
			"wavedashArena.assetbundle"
		},
		{
			SoundBundleKey.cryoStation,
			"cryoStation.assetbundle"
		},
		{
			SoundBundleKey.combatLab,
			"combatLab.assetbundle"
		},
		{
			SoundBundleKey.combatLabAlt,
			"combatLabAlt.assetbundle"
		},
		{
			SoundBundleKey.maluMalu,
			"maluMalu.assetbundle"
		},
		{
			SoundBundleKey.maluMaluAlt,
			"maluMaluAlt.assetbundle"
		},
		{
			SoundBundleKey.forbiddenShrine,
			"forbiddenShrine.assetbundle"
		},
		{
			SoundBundleKey.forbiddenShrineAlt,
			"forbiddenShrineAlt.assetbundle"
		},
		{
			SoundBundleKey.shadowbriar,
			"shadowbriar.assetbundle"
		},
		{
			SoundBundleKey.shadowbriarAlt,
			"shadowbriarAlt.assetbundle"
		},
		{
			SoundBundleKey.cargo,
			"cargo.assetbundle"
		},
		{
			SoundBundleKey.ashaniPostGame,
			"ashaniPostGame.assetbundle"
		},
		{
			SoundBundleKey.kiddPostGame,
			"kiddPostGame.assetbundle"
		},
		{
			SoundBundleKey.xanaPostGame,
			"xanaPostGame.assetbundle"
		},
		{
			SoundBundleKey.raymerPostGame,
			"raymerPostGame.assetbundle"
		},
		{
			SoundBundleKey.zhurongPostGame,
			"zhurongPostGame.assetbundle"
		},
		{
			SoundBundleKey.afiPostGame,
			"afiPostGame.assetbundle"
		},
		{
			SoundBundleKey.weishanPostGame,
			"weishanPostGame.assetbundle"
		},
		{
			SoundBundleKey.ashaniStore,
			"ashaniStore.assetbundle"
		},
		{
			SoundBundleKey.kiddStore,
			"kiddStore.assetbundle"
		},
		{
			SoundBundleKey.xanaStore,
			"xanaStore.assetbundle"
		},
		{
			SoundBundleKey.raymerStore,
			"raymerStore.assetbundle"
		},
		{
			SoundBundleKey.zhurongStore,
			"zhurongStore.assetbundle"
		},
		{
			SoundBundleKey.afiStore,
			"afiStore.assetbundle"
		},
		{
			SoundBundleKey.weishanStore,
			"weishanStore.assetbundle"
		},
		{
			SoundBundleKey.login,
			"login.assetbundle"
		},
		{
			SoundBundleKey.mainMenu,
			"mainMenu.assetbundle"
		},
		{
			SoundBundleKey.characterSelect,
			"characterSelect.assetbundle"
		},
		{
			SoundBundleKey.stageSelect,
			"stageSelect.assetbundle"
		},
		{
			SoundBundleKey.loadingBattle,
			"loadingBattle.assetbundle"
		},
		{
			SoundBundleKey.inGame,
			"inGame.assetbundle"
		},
		{
			SoundBundleKey.victoryScreen,
			"victoryScreen.assetbundle"
		},
		{
			SoundBundleKey.playerProgression,
			"playerProgression.assetbundle"
		},
		{
			SoundBundleKey.customLobby,
			"customLobby.assetbundle"
		},
		{
			SoundBundleKey.settings,
			"settings.assetbundle"
		},
		{
			SoundBundleKey.store,
			"store.assetbundle"
		},
		{
			SoundBundleKey.unboxing,
			"unboxing.assetbundle"
		},
		{
			SoundBundleKey.credits,
			"credits.assetbundle"
		}
	};

	// Token: 0x04000A0D RID: 2573
	private Dictionary<SoundBundleKey, SoundKey[]> bundleSounds = new Dictionary<SoundBundleKey, SoundKey[]>
	{
		{
			SoundBundleKey.generic,
			new SoundKey[]
			{
				SoundKey.generic_buttonHighlight,
				SoundKey.generic_dialogOpen,
				SoundKey.generic_dialogClose,
				SoundKey.generic_arrowClickLeft,
				SoundKey.generic_arrowClickRight,
				SoundKey.generic_dropdownOpen,
				SoundKey.generic_dropdownClose,
				SoundKey.generic_toggleOn,
				SoundKey.generic_toggleOff,
				SoundKey.generic_typingCharacter,
				SoundKey.generic_typingBackspace,
				SoundKey.generic_screenForwardTransition,
				SoundKey.generic_screenBackTransition,
				SoundKey.generic_dynamicMoveActivate,
				SoundKey.generic_powerMoveActivate,
				SoundKey.generic_dynamicMoveDenied,
				SoundKey.generic_powerMoveDenied
			}
		},
		{
			SoundBundleKey.wavedashArena,
			new SoundKey[]
			{
				SoundKey.wavedashArena_music
			}
		},
		{
			SoundBundleKey.cryoStation,
			new SoundKey[]
			{
				SoundKey.cryoStation_music
			}
		},
		{
			SoundBundleKey.combatLab,
			new SoundKey[]
			{
				SoundKey.combatLab_music
			}
		},
		{
			SoundBundleKey.combatLabAlt,
			new SoundKey[]
			{
				SoundKey.combatLabAlt_music
			}
		},
		{
			SoundBundleKey.maluMalu,
			new SoundKey[]
			{
				SoundKey.maluMalu_music
			}
		},
		{
			SoundBundleKey.maluMaluAlt,
			new SoundKey[]
			{
				SoundKey.maluMaluAlt_music
			}
		},
		{
			SoundBundleKey.forbiddenShrine,
			new SoundKey[]
			{
				SoundKey.forbiddenShrine_music
			}
		},
		{
			SoundBundleKey.forbiddenShrineAlt,
			new SoundKey[]
			{
				SoundKey.forbiddenShrineAlt_music
			}
		},
		{
			SoundBundleKey.shadowbriar,
			new SoundKey[]
			{
				SoundKey.shadowbriar_music
			}
		},
		{
			SoundBundleKey.shadowbriarAlt,
			new SoundKey[]
			{
				SoundKey.shadowbriarAlt_music
			}
		},
		{
			SoundBundleKey.cargo,
			new SoundKey[]
			{
				SoundKey.cargo_music
			}
		},
		{
			SoundBundleKey.ashaniPostGame,
			new SoundKey[]
			{
				SoundKey.ashaniPostGame_levelup
			}
		},
		{
			SoundBundleKey.kiddPostGame,
			new SoundKey[]
			{
				SoundKey.kiddPostGame_levelup
			}
		},
		{
			SoundBundleKey.xanaPostGame,
			new SoundKey[]
			{
				SoundKey.xanaPostGame_levelup
			}
		},
		{
			SoundBundleKey.raymerPostGame,
			new SoundKey[]
			{
				SoundKey.raymerPostGame_levelup
			}
		},
		{
			SoundBundleKey.zhurongPostGame,
			new SoundKey[]
			{
				SoundKey.zhurongPostGame_levelup
			}
		},
		{
			SoundBundleKey.afiPostGame,
			new SoundKey[]
			{
				SoundKey.afiPostGame_levelup
			}
		},
		{
			SoundBundleKey.weishanPostGame,
			new SoundKey[]
			{
				SoundKey.weishanPostGame_levelup
			}
		},
		{
			SoundBundleKey.ashaniStore,
			new SoundKey[]
			{
				SoundKey.ashaniStore_purchaseItem
			}
		},
		{
			SoundBundleKey.kiddStore,
			new SoundKey[]
			{
				SoundKey.kiddStore_purchaseItem
			}
		},
		{
			SoundBundleKey.xanaStore,
			new SoundKey[]
			{
				SoundKey.xanaStore_purchaseItem
			}
		},
		{
			SoundBundleKey.raymerStore,
			new SoundKey[]
			{
				SoundKey.raymerStore_purchaseItem
			}
		},
		{
			SoundBundleKey.zhurongStore,
			new SoundKey[]
			{
				SoundKey.zhurongStore_purchaseItem
			}
		},
		{
			SoundBundleKey.afiStore,
			new SoundKey[]
			{
				SoundKey.afiStore_purchaseItem
			}
		},
		{
			SoundBundleKey.weishanStore,
			new SoundKey[]
			{
				SoundKey.weishanStore_purchaseItem
			}
		},
		{
			SoundBundleKey.login,
			new SoundKey[]
			{
				SoundKey.login_accountCreationConfirmed,
				SoundKey.login_accountCreationError
			}
		},
		{
			SoundBundleKey.mainMenu,
			new SoundKey[]
			{
				SoundKey.mainMenu_music,
				SoundKey.mainMenu_mainMenuFoldoutOpen,
				SoundKey.mainMenu_mainMenuFoldoutClose,
				SoundKey.mainMenu_queueStart,
				SoundKey.mainMenu_queueStop
			}
		},
		{
			SoundBundleKey.characterSelect,
			new SoundKey[]
			{
				SoundKey.characterSelect_characterSelectScreenOpen,
				SoundKey.characterSelect_onlineBlindPickScreenOpen,
				SoundKey.characterSelect_characterHighlight,
				SoundKey.characterSelect_characterSelect,
				SoundKey.characterSelect_characterDeselect,
				SoundKey.characterSelect_randomHighlight,
				SoundKey.characterSelect_randomSelect,
				SoundKey.characterSelect_randomDeselect,
				SoundKey.characterSelect_skinCycle,
				SoundKey.characterSelect_teamCycle,
				SoundKey.characterSelect_totemPartnerCycle,
				SoundKey.characterSelect_ruleSetDelete,
				SoundKey.characterSelect_ruleSetAdd,
				SoundKey.characterSelect_ruleSetSelect
			}
		},
		{
			SoundBundleKey.stageSelect,
			new SoundKey[]
			{
				SoundKey.stageSelect_stageSelectScreenOpen,
				SoundKey.stageSelect_stageStrike,
				SoundKey.stageSelect_stageUnstrike,
				SoundKey.stageSelect_stageStikesReset
			}
		},
		{
			SoundBundleKey.loadingBattle,
			new SoundKey[]
			{
				SoundKey.loadingBattle_loadingBattleScreenOpen
			}
		},
		{
			SoundBundleKey.inGame,
			new SoundKey[]
			{
				SoundKey.inGame_exitGame,
				SoundKey.inGame_endGame,
				SoundKey.inGame_pause,
				SoundKey.inGame_unpause,
				SoundKey.inGame_flyout,
				SoundKey.inGame_flyout_small,
				SoundKey.inGame_tumbleHitGround
			}
		},
		{
			SoundBundleKey.victoryScreen,
			new SoundKey[]
			{
				SoundKey.victoryScreen_victoryScreenOpen
			}
		},
		{
			SoundBundleKey.playerProgression,
			new SoundKey[]
			{
				SoundKey.playerProgression_playerProgressionScreenOpen,
				SoundKey.playerProgression_experienceTick,
				SoundKey.playerProgression_levelUp
			}
		},
		{
			SoundBundleKey.customLobby,
			new SoundKey[]
			{
				SoundKey.customLobby_customLobbyScreenOpen,
				SoundKey.customLobby_customLobbyPlayerJoined,
				SoundKey.customLobby_customLobbyPlayerLeft
			}
		},
		{
			SoundBundleKey.settings,
			new SoundKey[]
			{
				SoundKey.settings_settingsScreenOpen,
				SoundKey.settings_controlBindingSelect,
				SoundKey.settings_controlBindingSet,
				SoundKey.settings_settingsReset,
				SoundKey.settings_settingsTabChange,
				SoundKey.settings_soundEffectSliderSet
			}
		},
		{
			SoundBundleKey.store,
			new SoundKey[]
			{
				SoundKey.store_music,
				SoundKey.store_storeScreenOpen,
				SoundKey.store_characterEquipViewOpen,
				SoundKey.store_characterEquipViewClosed,
				SoundKey.store_collectiblesEquipViewOpen,
				SoundKey.store_collectiblesEquipViewClosed,
				SoundKey.store_miniCharacterSelected,
				SoundKey.store_categorySelected,
				SoundKey.store_equipmentSelected,
				SoundKey.store_itemEquip,
				SoundKey.store_storeTabChange,
				SoundKey.store_purchaseDialogOpened,
				SoundKey.store_purchaseConfirmed
			}
		},
		{
			SoundBundleKey.unboxing,
			new SoundKey[]
			{
				SoundKey.unboxing_music,
				SoundKey.unboxing_openUnboxingScene,
				SoundKey.unboxing_exitUnboxingScene,
				SoundKey.unboxing_clickOpenBox,
				SoundKey.unboxing_clickOpenBoxButton,
				SoundKey.unboxing_crystalDrop,
				SoundKey.unboxing_portalAppear,
				SoundKey.unboxing_blueFlashSide,
				SoundKey.unboxing_blueFlashCenter,
				SoundKey.unboxing_highlight,
				SoundKey.unboxing_currency,
				SoundKey.unboxing_itemSideCommon,
				SoundKey.unboxing_itemSideUncommon,
				SoundKey.unboxing_itemSideRare,
				SoundKey.unboxing_itemSideLegendary,
				SoundKey.unboxing_itemCenterCommon,
				SoundKey.unboxing_itemCenterUncommon,
				SoundKey.unboxing_itemCenterRare,
				SoundKey.unboxing_itemCenterLegendary
			}
		},
		{
			SoundBundleKey.credits,
			new SoundKey[]
			{
				SoundKey.credits_music
			}
		}
	};
}
